#!/bin/bash
# Trae Agent Activation Script
# Creates system alias and starts the Trae Agent

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Banner
echo -e "${PURPLE}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                    🚀 TRAE AGENT ACTIVATOR 🚀                ║"
echo "║                                                              ║"
echo "║              Autonomous AI Development Platform              ║"
echo "║                     51 Tools Ready                          ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Get the absolute path of the script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TRAE_AGENT_DIR="$SCRIPT_DIR"

echo -e "${CYAN}🔍 Trae Agent Directory: ${TRAE_AGENT_DIR}${NC}"

# Check if we're in the right directory
if [[ ! -f "$TRAE_AGENT_DIR/trae_agent/cli.py" ]]; then
    echo -e "${RED}❌ Error: trae_agent/cli.py not found in $TRAE_AGENT_DIR${NC}"
    echo -e "${YELLOW}💡 Make sure you're running this script from the trae-agent root directory${NC}"
    exit 1
fi

# Function to create the system alias
create_system_alias() {
    echo -e "${BLUE}🔧 Creating system alias 'on-your-feet-agent'...${NC}"
    
    # Create the alias script
    ALIAS_SCRIPT="/usr/local/bin/on-your-feet-agent"
    
    # Create the alias script content
    cat > /tmp/on-your-feet-agent << ALIAS_EOF
#!/bin/bash
# Trae Agent System Alias
# Auto-generated by activate-agent.sh

cd "$TRAE_AGENT_DIR"

echo -e "\033[0;35m"
echo "🚀 TRAE AGENT STARTING UP..."
echo "📍 Location: $TRAE_AGENT_DIR"
echo "🛠️  51 Tools Loading..."
echo -e "\033[0m"

# Start Trae Agent CLI
uv run python -m trae_agent.cli "\$@"
ALIAS_EOF

    # Try to install the alias (requires sudo)
    if sudo cp /tmp/on-your-feet-agent "$ALIAS_SCRIPT" 2>/dev/null; then
        sudo chmod +x "$ALIAS_SCRIPT"
        echo -e "${GREEN}✅ System alias created: 'on-your-feet-agent'${NC}"
        echo -e "${GREEN}   You can now run: on-your-feet-agent${NC}"
    else
        echo -e "${YELLOW}⚠️  Could not create system alias (no sudo access)${NC}"
        echo -e "${YELLOW}   Creating local alias instead...${NC}"
        
        # Create local alias in user's shell config
        SHELL_CONFIG=""
        if [[ -f "$HOME/.bashrc" ]]; then
            SHELL_CONFIG="$HOME/.bashrc"
        elif [[ -f "$HOME/.zshrc" ]]; then
            SHELL_CONFIG="$HOME/.zshrc"
        fi
        
        if [[ -n "$SHELL_CONFIG" ]]; then
            # Remove existing alias if present
            sed -i '/alias on-your-feet-agent=/d' "$SHELL_CONFIG" 2>/dev/null || true
            
            # Add new alias
            echo "alias on-your-feet-agent='cd \"$TRAE_AGENT_DIR\" && uv run python -m trae_agent.cli'" >> "$SHELL_CONFIG"
            echo -e "${GREEN}✅ Local alias added to $SHELL_CONFIG${NC}"
            echo -e "${GREEN}   Run: source $SHELL_CONFIG${NC}"
            echo -e "${GREEN}   Then: on-your-feet-agent${NC}"
        fi
    fi
    
    # Clean up temp file
    rm -f /tmp/on-your-feet-agent
}

# Function to start Trae Agent directly
start_trae_agent() {
    echo -e "${BLUE}🚀 Starting Trae Agent directly...${NC}"
    
    # Change to the correct directory
    cd "$TRAE_AGENT_DIR"
    
    echo -e "${GREEN}📍 Working directory: $(pwd)${NC}"
    echo -e "${GREEN}🛠️  Loading 51 tools...${NC}"
    
    # Start the CLI
    uv run python -m trae_agent.cli "$@"
}

# Main execution
echo -e "${CYAN}🎯 Choose an option:${NC}"
echo -e "${CYAN}  1) Create system alias 'on-your-feet-agent' and start${NC}"
echo -e "${CYAN}  2) Just start Trae Agent now${NC}"
echo -e "${CYAN}  3) Create alias only (don't start)${NC}"

read -p "Enter choice (1-3): " choice

case $choice in
    1)
        create_system_alias
        echo -e "${GREEN}🚀 Starting Trae Agent...${NC}"
        start_trae_agent "$@"
        ;;
    2)
        start_trae_agent "$@"
        ;;
    3)
        create_system_alias
        echo -e "${GREEN}✅ Alias created. You can now run: on-your-feet-agent${NC}"
        ;;
    *)
        echo -e "${RED}❌ Invalid choice. Starting Trae Agent directly...${NC}"
        start_trae_agent "$@"
        ;;
esac
