name: CI

on:
  push:
    branches: [ main, mentat-*, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install -e . --no-deps
          pip install pytest ruff click PyYAML httpx
      - name: Ruff
        run: |
          ruff version || pip install ruff
          ruff check trae_agent
      - name: Pytest (subset)
        run: |
          pytest -q trae_agent/tests
